# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc ""
  homepage ""
  version "0.0.0"
  depends_on :macos

  on_macos do
    url "https://github.com/ianconsolata/homebrew-lotus/releases/download/v0.0.0/lotus_0.0.0_darwin-all.tar.gz"
    sha256 "b1011ba2abebe18f8f1cefc0df644da90c82849083495f0b99b41a2d9eeda328"

    def install
      bin.install "lotus"
      bin.install "lotus-miner"
      bin.install "lotus-worker"
    end
  end

  depends_on "pkg-config"
  depends_on "go"
  depends_on "jq"
  depends_on "bzr"
  depends_on "rustup-init"
  depends_on "hwloc"
end
