# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc "A homebrew cask for installing filecoin-project/lotus on MacOS"
  homepage "https://filecoin.io"
  version "20.20.51"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/ianconsolata/lotus/releases/download/v20.20.51/lotus_v20.20.51_darwin_all.tar.gz"
    sha256 "ecf6fc1267b38288ede47a86eed56d1b4789fcdd3992cc42a4b25bd38b0e9a3c"

    def install
      bin.install "lotus"
      bin.install "lotus-miner"
      bin.install "lotus-worker"
    end
  end

  depends_on "pkg-config"
  depends_on "jq"
  depends_on "bzr"
  depends_on "hwloc"

  test do
    system "#{bin}/lotus --version"
    system "#{bin}/lotus-miner --version"
    system "#{bin}/lotus-worker --version"
  end
end
