# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc "A homebrew cask for installing filecoin-project/lotus on MacOS"
  homepage "https://filecoin.io"
  version "40.40.50"
  license "MIT"
  depends_on :macos

  on_macos do
    url "https://github.com/ianconsolata/lotus/releases/download/v40.40.50/lotus_40.40.50_darwin_all.tar.gz"
    sha256 "cfbbf6d73a147cb5d69bd2b87f5779dbdd97fdeca06cd56b7af55008b3292114"

    def install
      bin.install "lotus"
      bin.install "lotus-miner"
      bin.install "lotus-worker"
    end
  end

  depends_on "pkg-config"
  depends_on "jq"
  depends_on "bzr"
  depends_on "hwloc"

  test do
    system "#{bin}/lotus --version"
    system "#{bin}/lotus-miner --version"
    system "#{bin}/lotus-worker --version"
  end
end
