# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lotus < Formula
  desc "A homebrew cask for installing filecoin-project/lotus on MacOS"
  homepage "https://filecoin.io"
  version "20.20.45"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ianconsolata/lotus/releases/download/v20.20.45/lotus_20.20.45_darwin_arm64.tar.gz"
      sha256 "cc6f1a476f753678156d4cafdd8b216c30d7725517b97665fb6b59b37956f973"

      def install
        bin.install "lotus"
        bin.install "lotus-miner"
        bin.install "lotus-worker"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ianconsolata/lotus/releases/download/v20.20.45/lotus_20.20.45_darwin_amd64.tar.gz"
      sha256 "ae5d23a9149eac8541c6271900f0cf4ff50c448888d15f0377b445f7d997ae2a"

      def install
        bin.install "lotus"
        bin.install "lotus-miner"
        bin.install "lotus-worker"
      end
    end
  end

  depends_on "pkg-config"
  depends_on "jq"
  depends_on "bzr"
  depends_on "hwloc"

  test do
    system "#{bin}/lotus --version"
    system "#{bin}/lotus-miner --version"
    system "#{bin}/lotus-worker --version"
  end
end
